### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by fearnlj01** [Track44/Track44Site#4]
Sorry for the email ;_;

**Comment by MiakoMoto** [comment]
`calm down hahhh`

**Comment by fearnlj01** [comment]
http://i.imgur.com/cYJJp2f.png

**Comment by MiakoMoto** [comment]
I see that on Canary but not ''regular'' discord

**Comment by fearnlj01** [comment]
Yeah, you need to have Admin access to be able to play with Webhooks and you can only do it in the Canary build for... ¯_(ツ)_/¯ reasons.
